[package]
name = "rust-bot"
version = "0.1.0"
authors = ["Rustlang-by community"]
edition = "2021"

[dependencies]
teloxide = { version = "0.11.3", features = ["macros"] }
log = "0.4.16"
pretty_env_logger = "0.4.0"
tokio = { version = "1.24.1", features = ["rt-multi-thread", "macros"] }

regex = "1.7.0"
chrono = "0.4.23"

sqlx = { version = "0.6", features = ["postgres", "runtime-tokio-native-tls", "chrono"] }
