[package]
name = "rust-bot"
version = "0.1.0"
authors = ["Rustlang-by community"]
edition = "2021"

[dependencies]
teloxide = { version = "0.10.1", features = ["auto-send", "macros"] }
log = "0.4.16"
pretty_env_logger = "0.4.0"
tokio = { version = "1.20.1", features = ["rt-multi-thread", "macros"] }

regex = "1.6.0"
chrono = "0.4.19"

sqlx = { version = "0.6", features = ["postgres", "runtime-tokio-native-tls", "chrono"] }