[package]
name = "rust-bot"
version = "0.1.0"
authors = ["Rustlang-by community"]
edition = "2021"

[dependencies]
teloxide = { version = "0.12.2", features = ["macros"] }
log = "0.4.16"
pretty_env_logger = "0.4.0"
tokio = { version = "1.26.0", features = ["rt-multi-thread", "macros"] }

regex = "1.7.3"
chrono = "0.4.24"

sqlx = { version = "0.6", features = ["postgres", "runtime-tokio-native-tls", "chrono"] }

reqwest = { version = "0.11", features = ["json"] }
serde = "1.0.158"
redis = { version = "0.22.3", features = ["json"] }

lazy_static = "1.4.0"
